[package]
name = "eodbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emacs = "0.18.0"
anyhow = "1.0.52"
serde = {version = "1.0.133", features = ['derive']}
lexpr = "0.2.6"
serde-lexpr = "0.1.2"
futures = { version = "0.3.19" }
smol = "1.2.5"
odbc-api = "0.33.0"
eodbc_macros = {path="eodbc_macros"}


[dev-dependencies]
emacs-rs-module = "0.18.0"


[lib]
crate-type = ["cdylib", "lib"]

