[package]
name = "eodbc_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.15"
proc-macro2 = "1.0"
syn = {version = "1.0.86", default-features = true, features = ["full", "visit"]}

[lib]
proc-macro = true
